export const navLinks = [
  {
    label: "Home",
    path: "/",
  },
  {
    label: "Buy",
    path: "/buy",
  },
  {
    label: "Sell",
    path: "/sell",
  },
  {
    label: "Rent",
    path: "/rent",
  },
  {
    label: "Contact",
    path: "/contact",
  },
];

export const cardInfo = [
  {
    name: "The Loft Life",
    image: require("@/images/image.jpg"),
    address: "14 High street",
    price: 24588,
    bed: 3,
    bath: 2,
    occupants: 2,
    rating: 4.85,
  },
  {
    name: "The Loft Life",
    image: require("@/images/image.jpg"),
    address: "14 High street",
    price: 24588,
    bed: 3,
    bath: 2,
    occupants: 2,
    rating: 4.85,
  },
  {
    name: "The Loft Life",
    image: require("@/images/image.jpg"),
    address: "14 High street",
    price: 24588,
    bed: 3,
    bath: 2,
    occupants: 2,
    rating: 4.85,
  },
  {
    name: "The Loft Life",
    image: require("@/images/image.jpg"),
    address: "14 High street",
    price: 24588,
    bed: 3,
    bath: 2,
    occupants: 2,
    rating: 4.85,
  },
  {
    name: "The Loft Life",
    image: require("@/images/image.jpg"),
    address: "14 High street",
    price: 24588,
    bed: 3,
    bath: 2,
    occupants: 2,
    rating: 4.85,
  },
  {
    name: "The Loft Life",
    image: require("@/images/image.jpg"),
    address: "14 High street",
    price: 24588,
    bed: 3,
    bath: 2,
    occupants: 2,
    rating: 4.85,
  },
  {
    name: "The Loft Life",
    image: require("@/images/image.jpg"),
    address: "14 High street",
    price: 24588,
    bed: 3,
    bath: 2,
    occupants: 2,
    rating: 4.85,
  },
];
